excluded:
  - Pods
  - SwiftLint

disabled_rules:
  - type_name
  - force_cast
  - trailing_whitespace
  - line_length

line_length:
  - 200 #warning
  - 300 #error

file_length:
  - 600  #warning
  - 1200 #error
